### ISSUE TITLE
CHANGELOG entries

### ISSUE THREAD

**Issue by ddellamico** [devdigital/git-flow-standard-version#1]
Hi ! Thanks for this repo, really useful.

Following your flow ( trying release ), I got CHANGELOG entries added multiple times ...
Maybe should I only generate CHANGELOGs from the master branch ?

regards,

Damien

**Comment by devdigital** [comment]
Hi Damien, yes we've found this, the general recommendation is to not use conventional commits for your commits in your feature branches, and then squash and merge into `master` and use a conventional commit at that point. This assumes each PR is a single feature or fix, and doesn't contain multiple fixes or features. Need to look at updating the docs. Happy to accept PRs!

**Comment by ddellamico** [comment]
Thank you for your fast reply ! Ok, so the best practice in this case is to generate the changelog in master branch. At this point do you create the tag with git flow or standard-version ?

**Comment by devdigital** [comment]
From the docs, tagging is turned off from standard-version in the `package.json` with:

```json
"standard-version": {
    "skip": {
        "tag": true
    }
}
```

**Comment by ddellamico** [comment]
Eventually I ended up to disable gitflow tagging using this command:

`git config gitflow.release.finish.notag yes`

I run this along with other configurations in a postinstall script in package.json.

Thanks again for this repo and your replies.

Regards,

Damien
